### ISSUE TITLE
This inscription will cause the server to freeze

### ISSUE THREAD

**Issue by liuleirain** [mir-ethernity/mir-eternal#196]
3001-3-精神力法-3-道法印
The following is the information returned by the log：

Error message:
The given key '0' was not present in the dictionary.
Stack information:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at GameServer.Templates.SkillInstance.Process() in E:\mir-eternal\GameServer\Templates\SkillInstance.cs:line 619
   at GameServer.Maps.PlayerObject.Process() in E:\mir-eternal\GameServer\Maps\PlayerObject.cs:line 1479
   at GameServer.Maps.MapGatewayProcess.Process() in E:\mir-eternal\GameServer\Maps\MapGatewayProcess.cs:line 670
   at GameServer.MainProcess.MainLoop() in E:\mir-eternal\GameServer\MainProcess.cs:line 93

**Comment by liuleirain** [comment]
2535-3-魔法护盾-3-逢生印
This seal will also crash the engine server：

Error message:
Collection was modified; enumeration operation may not execute.
Stack information:
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at GameServer.Maps.PlayerObject.Process() in D:\20221006\mir-eternal-main\GameServer\Maps\PlayerObject.cs:line 1481
   at GameServer.Maps.MapGatewayProcess.Process() in D:\20221006\mir-eternal-main\GameServer\Maps\MapGatewayProcess.cs:line 670
   at GameServer.MainProcess.MainLoop() in D:\20221006\mir-eternal-main\GameServer\MainProcess.cs:line 93
